version: '3.8'

services:
  backend:
    build:
      context: ./Bot/backend
      dockerfile: Dockerfile
    container_name: jarbasbot-backend
    ports:
      - "8080:80"
    env_file:
      - .env  # variáveis de ambiente seguras (OPENROUTER_API_KEY)
    restart: unless-stopped

  frontend:
    build:
      context: ./Bot/frontend
      dockerfile: Dockerfile
    container_name: jarbasbot-frontend
    ports:
      - "8081:80"
    restart: unless-stopped
